name = "shop-soledrop-worker"
main = "worker.js"
compatibility_date = "2024-09-23"

# Set secrets via: wrangler secret put SECRET_KEY
#                  wrangler secret put APP_PASSWORD
#                  wrangler secret put INCIDENT_KEY
[vars]
APP_USERNAME = "admin"

[[kv_namespaces]]
binding = "INCIDENT_KV"
id = "68f6f57e9f2f43bea0117c55d15c25ee"
preview_id = "68f6f57e9f2f43bea0117c55d15c25ee"
